swagger: '2.0'
info:
  description: 'This is the [Aeternity](https://www.aeternity.com/) compiler API.'
  version: 6.0.2
  title: Aeternity compiler
  termsOfService: 'https://www.aeternity.com/terms/'
  contact:
    email: apiteam@aeternity.com
basePath: /
schemes:
  - http
paths:
  /aci:
    post:
      operationId: 'GenerateACI'
      description: 'Generate an Aeternity Contract Interface (ACI) for contract'
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: contract code
          required: true
          schema:
            $ref: '#/definitions/Contract'
      responses:
        '200':
          description: 'ACI for contract'
          schema:
            $ref: '#/definitions/ACI'
        '400':
          description: Invalid input
          schema:
            $ref: '#/definitions/Error'
        '400':
          description: Compiler errors
          schema:
            $ref: '#/definitions/CompilerErrors'

  /compile:
    post:
      operationId: 'CompileContract'
      description: 'Compile a sophia contract from source and return byte code'
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: contract code
          required: true
          schema:
            $ref: '#/definitions/Contract'
      responses:
        '200':
          description: Byte code response
          schema:
            $ref: '#/definitions/ByteCode'
        '400':
          description: Invalid data
          schema:
            $ref: '#/definitions/Error'
        '400':
          description: Invalid contract
          schema:
            $ref: '#/definitions/CompilerErrors'

  /decode-data:
    post:
      operationId: 'DecodeData'
      description: 'Decode data as retuned by a contract call. - Legacy decoding'
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Binary data in Sophia ABI format
          required: true
          schema:
            $ref: '#/definitions/SophiaBinaryData'
      responses:
        '200':
          description: Json encoded data
          schema:
            $ref: '#/definitions/SophiaJsonData'
        '400':
          description: Invalid data
          schema:
            $ref: '#/definitions/Error'
        '400':
          description: Invalid data
          schema:
            $ref: '#/definitions/CompilerErrors'

  /decode-call-result:
    post:
      operationId: 'DecodeCallResult'
      description: 'Decode the result of contract call'
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Binary data in Sophia ABI format
          required: true
          schema:
            $ref: '#/definitions/SophiaCallResultInput'
      responses:
        '200':
          description: Json encoded data
          schema:
            $ref: '#/definitions/SophiaCallResult'
        '400':
          description: Invalid data
          schema:
            $ref: '#/definitions/Error'
        '400':
          description: Invalid data
          schema:
            $ref: '#/definitions/CompilerErrors'

  /decode-call-result/bytecode:
    post:
      operationId: 'DecodeCallResultBytecode'
      description: 'Decode the result of contract call from Bytecode'
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Call result + compiled contract
          required: true
          schema:
            $ref: '#/definitions/BytecodeCallResultInput'
      responses:
        '200':
          description: Json encoded data
          schema:
            $ref: '#/definitions/DecodedCallresult'
        '400':
          description: Invalid data
          schema:
            $ref: '#/definitions/Error'
        '400':
          description: Invalid data
          schema:
            $ref: '#/definitions/CompilerErrors'

  /encode-calldata:
    post:
      operationId: 'EncodeCalldata'
      description: 'Encode Sophia function call according to sophia ABI.'
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: 'Sophia function call - contract code + function name + arguments'
          required: true
          schema:
            $ref: '#/definitions/FunctionCallInput'
      responses:
        '200':
          description: Binary encoded calldata
          schema:
            $ref: '#/definitions/Calldata'
        '400':
          description: Invalid data
          schema:
            $ref: '#/definitions/Error'
        '400':
          description: Invalid contract
          schema:
            $ref: '#/definitions/CompilerErrors'

  /decode-calldata/bytecode:
    post:
      operationId: 'DecodeCalldataBytecode'
      description: 'Identify function name and arguments in Calldata for a compiled contract'
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: 'Calldata + compiled contract'
          required: true
          schema:
            $ref: '#/definitions/DecodeCalldataBytecode'
      responses:
        '200':
          description: Binary encoded calldata
          schema:
            $ref: '#/definitions/DecodedCalldata'
        '400':
          description: Invalid data
          schema:
            $ref: '#/definitions/Error'
        '400':
          description: Invalid contract
          schema:
            $ref: '#/definitions/Error'

  /decode-calldata/source:
    post:
      operationId: 'DecodeCalldataSource'
      description: 'Identify function name and arguments in Calldata for a (partial) contract'
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: 'Calldata + contract (stub) code'
          required: true
          schema:
            $ref: '#/definitions/DecodeCalldataSource'
      responses:
        '200':
          description: Binary encoded calldata
          schema:
            $ref: '#/definitions/DecodedCalldata'
        '400':
          description: Invalid data
          schema:
            $ref: '#/definitions/Error'
        '400':
          description: Invalid data
          schema:
            $ref: '#/definitions/CompilerErrors'

  /fate-assembler:
    post:
      operationId: 'GetFateAssemblerCode'
      description: 'Get FATE assembler code from bytecode'
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: contract byte array
          required: true
          schema:
            $ref: '#/definitions/ByteCodeInput'
      responses:
        '200':
          description: The FATE assembler
          schema:
            $ref: '#/definitions/FateAssembler'
        '400':
          description: Invalid data
          schema:
            $ref: '#/definitions/Error'


  /validate-byte-code:
    post:
      operationId: 'ValidateByteCode'
      description: 'Verify that an encoded byte array is the result of compiling a given contract'
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: contract byte array and source code
          required: true
          schema:
            $ref: '#/definitions/ValidateByteCodeInput'
      responses:
        '200':
          description: Validation successful
        '400':
          description: Invalid data
          schema:
            $ref: '#/definitions/Error'
        '400':
          description: Invalid contract
          schema:
            $ref: '#/definitions/CompilerErrors'

  /compiler-version:
    post:
      operationId: 'GetCompilerVersion'
      description: 'Extract compiler version from bytecode'
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: contract byte array
          required: true
          schema:
            $ref: '#/definitions/ByteCodeInput'
      responses:
        '200':
          description: The compiler version
          schema:
            $ref: '#/definitions/CompilerVersion'
        '400':
          description: Invalid data
          schema:
            $ref: '#/definitions/Error'

  /version:
    get:
      operationId: 'Version'
      description: 'Get the version of the underlying Sophia compiler version'
      produces:
        - application/json
      responses:
        '200':
          description: 'Sophia compiler version'
          schema:
            $ref: '#/definitions/CompilerVersion'
        '500':
          description: 'Error'
          schema:
            $ref: '#/definitions/Error'

  /api-version:
    get:
      operationId: 'APIVersion'
      description: 'Get the version of the API'
      produces:
        - application/json
      responses:
        '200':
          description: 'Sophia compiler version'
          schema:
            $ref: '#/definitions/APIVersion'
        '500':
          description: 'Error'
          schema:
            $ref: '#/definitions/Error'

  /api:
    get:
      operationId: 'Api'
      description: 'Get the Api description'
      produces:
        - application/json
      responses:
        '200':
          description: 'API description'
          schema:
            $ref: '#/definitions/API'
        '400':
          description: 'Error'
          schema:
            $ref: '#/definitions/Error'


definitions:
  Contract:
    type: object
    properties:
      code:
        type: string
      options:
        $ref: '#/definitions/CompileOpts'
    required:
      - code
      - options
  CompileOpts:
    type: object
    properties:
      backend:
        description: 'Compiler backend; fate | aevm'
        type: string
        enum: [ fate, aevm ]
      file_system:
        description: 'An explicit file system, mapping file names to file content'
        type: object
      src_file:
        description: 'Name of contract source file - only used in error messages'
        type: string
  APIVersion:
    type: object
    properties:
      api-version:
        description: 'API compiler version'
        type: string
    required:
      - api-version
  CompilerVersion:
    type: object
    properties:
      version:
        description: 'Sophia compiler version'
        type: string
    required:
      - version
  Error:
    type: object
    properties:
      reason:
        type: string
    required:
      - reason
  CompilerErrors:
    type: array
    items:
      $ref: '#/definitions/CompilerError'
  CompilerError:
    type: object
    properties:
      type:
        type: string
      pos:
        $ref: '#/definitions/ErrorPos'
      message:
        type: string
      context:
        type: string
    required:
      - type
      - pos
      - message
  ErrorPos:
    type: object
    properties:
      file:
        type: string
      line:
        type: integer
      col:
        type: integer
    required:
      - line
      - col
  ACI:
    type: object
    properties:
      encoded_aci:
        type: object
      external_encoded_aci:
        type: array
        items:
          type: object
      interface:
        type: string
    required:
      - encoded_aci
      - interface
  API:
    description: 'Swagger API description'
    type: object
  ByteCode:
    type: object
    properties:
      bytecode:
        $ref: '#/definitions/EncodedByteArray'
    required:
      - bytecode
  SophiaCallResultInput:
    type: object
    properties:
      source:
        description: '(Possibly partial) Sophia contract code/interface'
        type: string
      options:
        $ref: '#/definitions/CompileOpts'
      function:
        description: 'Name of the called function'
        type: string
      call-result:
        description: 'Call result type (ok | revert | error)'
        type: string
      call-value:
        description: 'Call result value (ABI encoded data or error string)'
        type: string
    required:
      - source
      - function
      - call-result
      - call-value
  SophiaCallResult: { }
  SophiaBinaryData:
    type: object
    properties:
      sophia-type:
        type: string
      data:
        type: string
    required:
      - sophia-type
      - data
  SophiaJsonData:
    type: object
    properties:
      data:
        type: object
    required:
      - data
  FunctionCallInput:
    type: object
    properties:
      source:
        description: '(Possibly partial) Sophia contract code'
        type: string
      options:
        $ref: '#/definitions/CompileOpts'
      function:
        description: 'Name of function to call'
        type: string
      arguments:
        description: 'Array of function call arguments'
        type: array
        items:
          type: string
    required:
      - source
      - function
      - arguments
  BytecodeCallResultInput:
    type: object
    properties:
      bytecode:
        description: 'Compiled contract'
        $ref: '#/definitions/EncodedByteArray'
      function:
        description: 'Name of the called function'
        type: string
      call-result:
        description: 'Call result type (ok | revert | error)'
        type: string
      call-value:
        description: 'Call result value (ABI encoded data or error string)'
        type: string
      backend:
        description: 'Compiler backend; fate | aevm'
        type: string
        enum: [ fate, aevm ]
    required:
      - function
      - call-result
      - call-value
      - bytecode
  DecodeCalldataBytecode:
    type: object
    properties:
      calldata:
        description: 'Calldata to dissect'
        $ref: '#/definitions/EncodedByteArray'
      bytecode:
        description: 'Compiled contract'
        $ref: '#/definitions/EncodedByteArray'
      backend:
        description: 'Compiler backend; fate | aevm'
        type: string
        enum: [ fate, aevm ]
    required:
      - calldata
      - bytecode
  DecodeCalldataSource:
    type: object
    properties:
      source:
        description: '(Possibly partial) Sophia contract code'
        type: string
      options:
        $ref: '#/definitions/CompileOpts'
      calldata:
        description: 'Calldata to dissect'
        $ref: '#/definitions/EncodedByteArray'
      function:
        description: 'Name of the function to call'
        type: string
    required:
      - calldata
      - function
      - source
  ByteCodeInput:
    type: object
    properties:
      bytecode:
        description: 'Compiled contract'
        $ref: '#/definitions/EncodedByteArray'
    required:
      - bytecode
  ValidateByteCodeInput:
    type: object
    properties:
      bytecode:
        description: 'Compiled contract'
        $ref: '#/definitions/EncodedByteArray'
      source:
        description: 'Sophia contract source code'
        type: string
      options:
        $ref: '#/definitions/CompileOpts'
    required:
      - bytecode
      - source
      - options
  DecodedCallresult:
    type: object
    properties:
      function:
        type: string
      result:
        type: object
    required:
      - function
      - result
  DecodedCalldata:
    type: object
    properties:
      function:
        type: string
      arguments:
        type: array
        items:
          type: object
    required:
      - function
      - arguments
  Calldata:
    type: object
    properties:
      calldata:
        $ref: '#/definitions/EncodedByteArray'
    required:
      - calldata
  EncodedByteArray:
    description: 'Prefixed (cb_) Base64Check encoded byte array'
    type: string
  FateAssembler:
    type: object
    properties:
      fate-assembler:
        description: 'Fate assembler code'
        type: string
    required:
      - fate-assembler
