name: Pull Request

on:
  pull_request:
    branches-ignore: [ '3.x' ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 15
      - name: Set up Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/libsodium
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Install libsodium
        run: |
          ./.github/scripts/install-libsodium.sh
          export PKG_CONFIG_PATH=$HOME/libsodium/lib/pkgconfig:$PKG_CONFIG_PATH
          export LD_LIBRARY_PATH=$HOME/libsodium/lib:$LD_LIBRARY_PATH
      - name: Set Environment Variables
        run: |
          echo "AETERNITY_GENERATE_SOURCES=true" >> $GITHUB_ENV
          echo "AETERNAL_BASE_URL=http://localhost:8080" >> $GITHUB_ENV
          echo "AETERNITY_BASE_URL=http://localhost" >> $GITHUB_ENV
          echo "COMPILER_BASE_URL=http://localhost:3080" >> $GITHUB_ENV
          echo "INDAEX_BASE_URL=http://localhost:4000" >> $GITHUB_ENV
      - name: Test & Build
        run: |
          docker-compose up -d
          ./gradlew integrationTest
          ./gradlew build
      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
      - name: Upload to Codecov
        uses: codecov/codecov-action@v1