name: Release

on:
  release:
    types: [ released, prereleased ]
    branches: [ '3.x' ]
    tags:
      - 'v3.*.*'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
      ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
      ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_PRIVATE_KEY }}
      ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
      CI_BUILD_NUMBER: ${{ github.run_number }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Set Environment Variables
        run: |
          echo "AETERNITY_GENERATE_SOURCES=true" >> $GITHUB_ENV
      - name: Extract version tag
        run: echo "BUILD_TAG=${GITHUB_REF:10}" >> $GITHUB_ENV
      - name: Publish Release
        run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties